name: Despliegue Hugo a Azure App Service

on:
  push:
    branches:
      - configuracion-azure # Ahora sí saltará cuando subas a esta rama
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          submodules: recursive # Vital para que cargue PaperMod
          fetch-depth: 0

      - name: Instalar Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Construir la web (Build)
        run: hugo --minify

      - name: Desplegar en Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'hmis-ior443'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./public # Subimos SOLO la carpeta compilada